.PHONY: bundle-install xxx-web

intage-web:
	itamae local \
		--node-json=nodes/intage/web.json \
			roles/common/base.rb \
			roles/common/developer-tools.rb \
			roles/common/web.rb \
			roles/intage/app.rb \
			roles/intage/db-client.rb
