.PHONY: bundle-install xxx-web

xxx-web:
	itamae local \
		--node-json=nodes/xxx/web.json \
			roles/common/base.rb \
			roles/common/util.rb \
			roles/common/developer-tools.rb \
			roles/common/web.rb \
			roles/xxx/app.rb \
			roles/xxx/db-client.rb
